/**
 * Water Sort Puzzle — Comprehensive Catalog System
 * 40 Unique Themes, 40 Unique Bottle Skins, 40 Unique Tube Styles
 */

export const THEMES_CATALOG = [
  { id: 'Classic', name: 'Classic Indigo', price: 0, bg: '#F8FAFF', colors: ['#EEF0FF', '#635BFF', '#8B5CF6'], desc: 'Clean, peaceful default vibe' },
  { id: 'Forest', name: 'Forest Mist', price: 100, bg: '#F0FDF4', colors: ['#F0FDF4', '#22C55E', '#16A34A'], desc: 'Serene botanical lush greens' },
  { id: 'Ocean', name: 'Ocean Tides', price: 150, bg: '#F0F9FF', colors: ['#F0F9FF', '#06B6D4', '#0284C7'], desc: 'Deep calm aquatic currents' },
  { id: 'Sunset', name: 'Sunset Glow', price: 200, bg: '#FFF7ED', colors: ['#FFF7ED', '#F97316', '#EA580C'], desc: 'Warm dusk amber radiance' },
  { id: 'Space', name: 'Space Nebula', price: 250, bg: '#FAF5FF', colors: ['#FAF5FF', '#A855F7', '#7E22CE'], desc: 'Cosmic twilight starlight' },
  { id: 'Winter', name: 'Glacial Frost', price: 300, bg: '#F8FAFC', colors: ['#F8FAFC', '#38BDF8', '#0284C7'], desc: 'Crisp Arctic chill breeze' },
  { id: 'Sakura', name: 'Cherry Blossom', price: 350, bg: '#FFF1F2', colors: ['#FFE4E6', '#FB7185', '#E11D48'], desc: 'Delicate pink spring petals' },
  { id: 'Desert', name: 'Sahara Mirage', price: 400, bg: '#FEFCE8', colors: ['#FEF08A', '#F59E0B', '#B45309'], desc: 'Golden dunes and warm sands' },
  { id: 'Emerald', name: 'Emerald Gem', price: 450, bg: '#ECFDF5', colors: ['#A7F3D0', '#10B981', '#047857'], desc: 'Rich glowing jewel tones' },
  { id: 'Amethyst', name: 'Amethyst Royal', price: 500, bg: '#F5F3FF', colors: ['#DDD6FE', '#8B5CF6', '#5B21B6'], desc: 'Regal crystalline magic' },
  { id: 'Ruby', name: 'Ruby Velvet', price: 550, bg: '#FFF1F2', colors: ['#FECDD3', '#F43F5E', '#BE123C'], desc: 'Deep passionate crimson' },
  { id: 'Sapphire', name: 'Sapphire Night', price: 600, bg: '#EFF6FF', colors: ['#BFDBFE', '#3B82F6', '#1D4ED8'], desc: 'Brilliant deep ocean blue' },
  { id: 'Amber', name: 'Honey Amber', price: 650, bg: '#FFFBEB', colors: ['#FDE68A', '#F59E0B', '#D97706'], desc: 'Sweet sunlit crystal drops' },
  { id: 'Coral', name: 'Coral Reef', price: 700, bg: '#FFF5F5', colors: ['#FFCCD5', '#FB7185', '#F43F5E'], desc: 'Vibrant tropical underwater' },
  { id: 'Lavender', name: 'Lavender Dream', price: 750, bg: '#FDF4FF', colors: ['#F5D0FE', '#C084FC', '#9333EA'], desc: 'Gentle calming lilac aroma' },
  { id: 'Mint', name: 'Fresh Peppermint', price: 800, bg: '#F0FDFA', colors: ['#99F6E4', '#2DD4BF', '#0D9488'], desc: 'Cool revitalizing eucalyptus' },
  { id: 'Lemon', name: 'Citrus Splash', price: 850, bg: '#FEFCE8', colors: ['#FEF08A', '#FACC15', '#CA8A04'], desc: 'Zesty energizing citrus' },
  { id: 'Volcano', name: 'Magma Flare', price: 900, bg: '#FFF1F1', colors: ['#FECACA', '#EF4444', '#B91C1C'], desc: 'Molten volcanic pulse' },
  { id: 'Cyberpunk', name: 'Neon Cyber', price: 950, bg: '#FAF5FF', colors: ['#F472B6', '#06B6D4', '#635BFF'], desc: 'Futuristic synthwave glow' },
  { id: 'Matcha', name: 'Zen Matcha', price: 1000, bg: '#F7FEE7', colors: ['#D9F99D', '#84CC16', '#4D7C0F'], desc: 'Traditional tranquil green tea' },
  { id: 'Peach', name: 'Sweet Peach', price: 1050, bg: '#FFF7ED', colors: ['#FFEDD5', '#FB923C', '#EA580C'], desc: 'Soft pastel summer fruit' },
  { id: 'Aurora', name: 'Northern Lights', price: 1100, bg: '#F0FDF4', colors: ['#6EE7B7', '#38BDF8', '#818CF8'], desc: 'Shimmering celestial curtain' },
  { id: 'Midnight', name: 'Midnight Shadow', price: 1150, bg: '#F1F5F9', colors: ['#CBD5E1', '#64748B', '#1E293B'], desc: 'Stealthy elegant dark hue' },
  { id: 'Gold', name: 'Imperial Gold', price: 1200, bg: '#FFFBEB', colors: ['#FEF08A', '#F59E0B', '#B45309'], desc: 'Dazzling royal treasure' },
  { id: 'Galaxy', name: 'Deep Cosmos', price: 1250, bg: '#FAF5FF', colors: ['#E9D5FF', '#A855F7', '#4C1D95'], desc: 'Starry intergalactic void' },
  { id: 'Oasis', name: 'Desert Oasis', price: 1300, bg: '#F0FDFA', colors: ['#CCFBF1', '#14B8A6', '#0F766E'], desc: 'Hidden crystal spring' },
  { id: 'Blossom', name: 'Lotus Blossom', price: 1350, bg: '#FDF2F8', colors: ['#FBCFE8', '#EC4899', '#BE185D'], desc: 'Serene floating river flower' },
  { id: 'Monochrome', name: 'Silver Minimal', price: 1400, bg: '#F8FAFC', colors: ['#E2E8F0', '#94A3B8', '#475569'], desc: 'Pure architectural modernism' },
  { id: 'SunsetBeach', name: 'Bikini Atoll', price: 1450, bg: '#FFF7ED', colors: ['#FED7AA', '#F97316', '#06B6D4'], desc: 'Turquoise water & warm sun' },
  { id: 'Prism', name: 'Prism Rainbow', price: 1500, bg: '#F8FAFF', colors: ['#F43F5E', '#FACC15', '#3B82F6'], desc: 'Refracted spectrum rays' },
  { id: 'Rainforest', name: 'Amazon Basin', price: 1550, bg: '#F0FDF4', colors: ['#BBF7D0', '#22C55E', '#15803D'], desc: 'Exotic tropical biodiversity' },
  { id: 'Candy', name: 'Bubblegum Sweet', price: 1600, bg: '#FFF1F2', colors: ['#FECDD3', '#F43F5E', '#A855F7'], desc: 'Playful confectionary pastel' },
  { id: 'Coffee', name: 'Caramel Macchiato', price: 1650, bg: '#FEFCE8', colors: ['#FDE68A', '#D97706', '#78350F'], desc: 'Warm comforting espresso' },
  { id: 'Iceberg', name: 'Polar Glacier', price: 1700, bg: '#F0F9FF', colors: ['#BAE6FD', '#0284C7', '#0369A1'], desc: 'Pure sub-zero transparency' },
  { id: 'Velvet', name: 'Royal Velvet', price: 1750, bg: '#FAF5FF', colors: ['#DDD6FE', '#7C3AED', '#4C1D95'], desc: 'Opulent aristocratic weave' },
  { id: 'Autumn', name: 'Autumn Maple', price: 1800, bg: '#FFF7ED', colors: ['#FED7AA', '#EA580C', '#9A3412'], desc: 'Crisp fallen golden foliage' },
  { id: 'Lagoon', name: 'Tropical Lagoon', price: 1850, bg: '#ECFEFF', colors: ['#A5F3FC', '#06B6D4', '#0891B2'], desc: 'Pristine island shoreline' },
  { id: 'Twilight', name: 'Twilight Ember', price: 1900, bg: '#FAF5FF', colors: ['#E9D5FF', '#EC4899', '#4338CA'], desc: 'Dusky purple sky gradient' },
  { id: 'CosmicRose', name: 'Cosmic Rose', price: 1950, bg: '#FFF1F2', colors: ['#FECDD3', '#E11D48', '#7E22CE'], desc: 'Interstellar floral beauty' },
  { id: 'Infinity', name: 'Infinity Nexus', price: 2000, bg: '#F8FAFF', colors: ['#635BFF', '#06B6D4', '#F59E0B'], desc: 'Master tier eternal spectrum' },
];

export const BOTTLES_CATALOG = [
  { id: 'default', name: 'Classic Bottle', skin: 'default', price: 0, desc: 'Classic ergonomic silhouette', layers: ['#3B82F6', '#06B6D4', '#FACC15', '#EC4899'] },
  { id: 'ocean', name: 'Ocean Flask', skin: 'ocean', price: 100, desc: 'Wave-sculpted nautical glass', layers: ['#0284C7', '#06B6D4', '#38BDF8', '#E0F2FE'] },
  { id: 'pastel', name: 'Pastel Teardrop', skin: 'pastel', price: 150, desc: 'Soft rounded belly flask', layers: ['#F472B6', '#FDE047', '#A78BFA', '#FBCFE8'] },
  { id: 'galaxy', name: 'Galaxy Prism', skin: 'galaxy', price: 200, desc: 'Faceted geometric shoulders', layers: ['#8B5CF6', '#EC4899', '#635BFF', '#C084FC'] },
  { id: 'leaf', name: 'Botanical Leaf', skin: 'leaf', price: 250, desc: 'Tapered organic contours', layers: ['#16A34A', '#22C55E', '#86EFAC', '#DCFCE7'] },
  { id: 'cherry', name: 'Potion Orb', skin: 'cherry', price: 300, desc: 'Spherical alchemist vessel', layers: ['#E11D48', '#F43F5E', '#FDA4AF', '#FFE4E6'] },
  { id: 'crystal_bottle', name: 'Diamond Carafe', skin: 'crystal_bottle', price: 350, desc: 'Faceted luxury crystal', layers: ['#38BDF8', '#818CF8', '#C084FC', '#E0E7FF'] },
  { id: 'vintage_bottle', name: 'Vintage Milk Bottle', skin: 'vintage_bottle', price: 400, desc: 'Retro straight-neck glass', layers: ['#F59E0B', '#10B981', '#3B82F6', '#EF4444'] },
  { id: 'hourglass', name: 'Hourglass Flask', skin: 'hourglass', price: 450, desc: 'Cinched waist balance', layers: ['#EC4899', '#8B5CF6', '#06B6D4', '#FACC15'] },
  { id: 'fluted', name: 'Fluted Amphora', skin: 'fluted', price: 500, desc: 'Greek architectural ribs', layers: ['#10B981', '#F59E0B', '#635BFF', '#EC4899'] },
  { id: 'bell_bottle', name: 'Bell Jar Potion', skin: 'bell_bottle', price: 550, desc: 'Wide dome base container', layers: ['#F43F5E', '#FBBF24', '#22C55E', '#3B82F6'] },
  { id: 'hexagonal', name: 'Hexagon Prism', skin: 'hexagonal', price: 600, desc: 'Sharp modern 6-sided body', layers: ['#635BFF', '#A855F7', '#EC4899', '#F43F5E'] },
  { id: 'droplet_bottle', name: 'Aqua Droplet', skin: 'droplet_bottle', price: 650, desc: 'Fluid teardrop contour', layers: ['#06B6D4', '#3B82F6', '#8B5CF6', '#EC4899'] },
  { id: 'alembic', name: 'Alembic Still', skin: 'alembic', price: 700, desc: 'Ancient laboratory copper style', layers: ['#EA580C', '#F59E0B', '#FBBF24', '#FEF08A'] },
  { id: 'square_bottle', name: 'Apothecary Cube', skin: 'square_bottle', price: 750, desc: 'Sturdy square apothecary jar', layers: ['#15803D', '#22C55E', '#86EFAC', '#BBF7D0'] },
  { id: 'flagon', name: 'Tavern Flagon', skin: 'flagon', price: 800, desc: 'Stout rounded medieval jug', layers: ['#B45309', '#D97706', '#F59E0B', '#FDE68A'] },
  { id: 'conical', name: 'Erlenmeyer Flask', skin: 'conical', price: 850, desc: 'Scientific conical beaker', layers: ['#7C3AED', '#A855F7', '#C084FC', '#E9D5FF'] },
  { id: 'spiral_bottle', name: 'Helical Spiral', skin: 'spiral_bottle', price: 900, desc: 'Twisting spiral grooves', layers: ['#2563EB', '#3B82F6', '#60A5FA', '#93C5FD'] },
  { id: 'heart_bottle', name: 'Cupid Heart', skin: 'heart_bottle', price: 950, desc: 'Whimsical romantic heart', layers: ['#E11D48', '#FB7185', '#FDA4AF', '#FFE4E6'] },
  { id: 'star_bottle', name: 'Celeste Star', skin: 'star_bottle', price: 1000, desc: 'Star-faceted mystical jar', layers: ['#F59E0B', '#FBBF24', '#FCD34D', '#FEF08A'] },
  { id: 'gourd', name: 'Wu Lou Gourd', skin: 'gourd', price: 1050, desc: 'Traditional double-sphere gourd', layers: ['#059669', '#10B981', '#34D399', '#A7F3D0'] },
  { id: 'barrel_bottle', name: 'Oak Cask Barrel', skin: 'barrel_bottle', price: 1100, desc: 'Bulbous stout barrel shape', layers: ['#9A3412', '#C2410C', '#EA580C', '#FB923C'] },
  { id: 'tall_neck', name: 'Swan Neck Flask', skin: 'tall_neck', price: 1150, desc: 'Elegant elongated bottleneck', layers: ['#4338CA', '#6366F1', '#818CF8', '#C7D2FE'] },
  { id: 'bulb_bottle', name: 'Lightbulb Decanter', skin: 'bulb_bottle', price: 1200, desc: 'Luminous lightbulb silhouette', layers: ['#D97706', '#F59E0B', '#FBBF24', '#FEF9C3'] },
  { id: 'amphora', name: 'Greco Amphora', skin: 'amphora', price: 1250, desc: 'Classical antiquities vessel', layers: ['#BE185D', '#DB2777', '#F472B6', '#FBCFE8'] },
  { id: 'flask_slim', name: 'Pocket Hip Flask', skin: 'flask_slim', price: 1300, desc: 'Curved metallic slim profile', layers: ['#334155', '#475569', '#64748B', '#94A3B8'] },
  { id: 'volumetric', name: 'Volumetric Chemistry', skin: 'volumetric', price: 1350, desc: 'Precision chemist graduation', layers: ['#0891B2', '#06B6D4', '#22D3EE', '#A5F3FC'] },
  { id: 'chalice', name: 'Royal Chalice', skin: 'chalice', price: 1400, desc: 'Ceremonial stemmed goblet', layers: ['#B45309', '#F59E0B', '#FBBF24', '#FEF08A'] },
  { id: 'canteen', name: 'Pioneer Canteen', skin: 'canteen', price: 1450, desc: 'Rugged circular canteen', layers: ['#15803D', '#16A34A', '#4ADE80', '#BBF7D0'] },
  { id: 'tulip_bottle', name: 'Tulip Decanter', skin: 'tulip_bottle', price: 1500, desc: 'Flared petal rim silhouette', layers: ['#C026D3', '#D946EF', '#E879F9', '#F5D0FE'] },
  { id: 'crystal_skull', name: 'Mayan Skull Bottle', skin: 'crystal_skull', price: 1550, desc: 'Mythical carved crystal relic', layers: ['#4F46E5', '#6366F1', '#A5B4FC', '#E0E7FF'] },
  { id: 'prism_flask', name: 'Triangular Prism', skin: 'prism_flask', price: 1600, desc: 'Sharp 3-sided modern angle', layers: ['#DC2626', '#EA580C', '#F59E0B', '#FBBF24'] },
  { id: 'potion_heart', name: 'Elixir of Life', skin: 'potion_heart', price: 1650, desc: 'Sacred heart potion jar', layers: ['#BE123C', '#E11D48', '#F43F5E', '#FDA4AF'] },
  { id: 'bamboo_bottle', name: 'Bamboo Node', skin: 'bamboo_bottle', price: 1700, desc: 'Natural bamboo segment vessel', layers: ['#15803D', '#22C55E', '#4ADE80', '#DCFCE7'] },
  { id: 'pyramid_bottle', name: 'Giza Pyramid', skin: 'pyramid_bottle', price: 1750, desc: 'Geometric 4-sided pyramid', layers: ['#CA8A04', '#EAB308', '#FACC15', '#FEF08A'] },
  { id: 'nebula_bottle', name: 'Nebula Orb', skin: 'nebula_bottle', price: 1800, desc: 'Deep cosmic star chamber', layers: ['#6B21A8', '#9333EA', '#C084FC', '#F3E8FF'] },
  { id: 'ice_flask', name: 'Glacial Monolith', skin: 'ice_flask', price: 1850, desc: 'Carved frosted ice block', layers: ['#0369A1', '#0284C7', '#38BDF8', '#E0F2FE'] },
  { id: 'phoenix_bottle', name: 'Phoenix Tear', skin: 'phoenix_bottle', price: 1900, desc: 'Winged fiery teardrop', layers: ['#B91C1C', '#DC2626', '#EA580C', '#F59E0B'] },
  { id: 'dragon_bottle', name: 'Dragon Scale', skin: 'dragon_bottle', price: 1950, desc: 'Textured mythical dragon flask', layers: ['#047857', '#059669', '#10B981', '#6EE7B7'] },
  { id: 'infinity_bottle', name: 'Infinity Relic', skin: 'infinity_bottle', price: 2000, desc: 'Supreme cosmic master vessel', layers: ['#635BFF', '#06B6D4', '#EC4899', '#FACC15'] },
];

export const TUBES_CATALOG = [
  { id: 'default', name: 'Classic Test Tube', styleType: 'default', price: 0, desc: 'Standard laboratory U-bottom tube', layers: ['#3B82F6', '#EC4899', '#FACC15', '#22C55E'] },
  { id: 'rounded', name: 'Rounded Capsule', styleType: 'rounded', price: 100, desc: 'Smooth capsule test tube', layers: ['#8B5CF6', '#3B82F6', '#06B6D4', '#635BFF'] },
  { id: 'crystal', name: 'Crystal Cut Tube', styleType: 'crystal', price: 150, desc: 'Chamfered faceted base corners', layers: ['#06B6D4', '#F97316', '#FACC15', '#EC4899'] },
  { id: 'rainbow', name: 'Chrome Band Tube', styleType: 'rainbow', price: 200, desc: 'Iridescent metallic rim band', layers: ['#EC4899', '#8B5CF6', '#3B82F6', '#22C55E'] },
  { id: 'bubble', name: 'Bubble Ribbed Tube', styleType: 'bubble', price: 250, desc: 'Undulating condensation ribs', layers: ['#F97316', '#FACC15', '#22C55E', '#3B82F6'] },
  { id: 'tall', name: 'Graduated Cylinder', styleType: 'tall', price: 300, desc: 'Elongated slender laboratory glass', layers: ['#635BFF', '#8B5CF6', '#EC4899', '#FACC15'] },
  { id: 'beaker_tube', name: 'Flared Lip Tube', styleType: 'beaker_tube', price: 350, desc: 'Flared pouring spout test tube', layers: ['#0284C7', '#38BDF8', '#F472B6', '#FBBF24'] },
  { id: 'conical_tube', name: 'Centrifuge Tube', styleType: 'conical_tube', price: 400, desc: 'Sharp V-shaped bottom tip', layers: ['#10B981', '#F59E0B', '#EF4444', '#3B82F6'] },
  { id: 'spiral_tube', name: 'Vortex Tube', styleType: 'spiral_tube', price: 450, desc: 'Swirling glass spiral walls', layers: ['#7C3AED', '#06B6D4', '#10B981', '#F59E0B'] },
  { id: 'frosted_tube', name: 'Frosted Quartz', styleType: 'frosted_tube', price: 500, desc: 'Velvety matte frosted finish', layers: ['#38BDF8', '#818CF8', '#C084FC', '#F472B6'] },
  { id: 'neon_tube', name: 'Neon Glow Tube', styleType: 'neon_tube', price: 550, desc: 'Electric phosphorescent rim', layers: ['#EC4899', '#06B6D4', '#FACC15', '#635BFF'] },
  { id: 'double_tube', name: 'Double Bulb Tube', styleType: 'double_tube', price: 600, desc: 'Dual sphere distillation chamber', layers: ['#F43F5E', '#FB923C', '#FBBF24', '#34D399'] },
  { id: 'steampunk_tube', name: 'Brass Gauge Tube', styleType: 'steampunk_tube', price: 650, desc: 'Victorian brass reinforcement', layers: ['#B45309', '#D97706', '#F59E0B', '#FEF08A'] },
  { id: 'prism_tube', name: 'Prism Hex Tube', styleType: 'prism_tube', price: 700, desc: 'Refractive prismatic facets', layers: ['#635BFF', '#EC4899', '#06B6D4', '#10B981'] },
  { id: 'quantum_tube', name: 'Quantum Core', styleType: 'quantum_tube', price: 750, desc: 'Subatomic particle container', layers: ['#06B6D4', '#3B82F6', '#8B5CF6', '#C084FC'] },
  { id: 'bamboo_tube', name: 'Bamboo Shoot', styleType: 'bamboo_tube', price: 800, desc: 'Organic bamboo cane segment', layers: ['#16A34A', '#22C55E', '#86EFAC', '#DCFCE7'] },
  { id: 'vulcan_tube', name: 'Volcanic Core', styleType: 'vulcan_tube', price: 850, desc: 'Heat-resistant obsidian glass', layers: ['#DC2626', '#EA580C', '#F59E0B', '#FBBF24'] },
  { id: 'glacier_tube', name: 'Arctic Stalactite', styleType: 'glacier_tube', price: 900, desc: 'Crystalline icicle test tube', layers: ['#0284C7', '#38BDF8', '#BAE6FD', '#E0F2FE'] },
  { id: 'emerald_tube', name: 'Emerald Vane', styleType: 'emerald_tube', price: 950, desc: 'Jeweled emerald mineral rim', layers: ['#047857', '#059669', '#10B981', '#6EE7B7'] },
  { id: 'gold_rim_tube', name: 'Gilded 24K Tube', styleType: 'gold_rim_tube', price: 1000, desc: 'Pure 24k gold leaf collar', layers: ['#CA8A04', '#EAB308', '#FACC15', '#FEF08A'] },
  { id: 'plasma_tube', name: 'Plasma Chamber', styleType: 'plasma_tube', price: 1050, desc: 'Ionized atmospheric glow', layers: ['#9333EA', '#C084FC', '#F472B6', '#FBCFE8'] },
  { id: 'bio_tube', name: 'Biohazard Vial', styleType: 'bio_tube', price: 1100, desc: 'Sealed biological specimen tube', layers: ['#84CC16', '#A3E635', '#BEF264', '#ECFCCB'] },
  { id: 'cyber_tube', name: 'Cyber Matrix', styleType: 'cyber_tube', price: 1150, desc: 'Digital grid etched glass', layers: ['#06B6D4', '#22D3EE', '#67E8F9', '#CFFAFE'] },
  { id: 'ruby_tube', name: 'Ruby Ampoule', styleType: 'ruby_tube', price: 1200, desc: 'Sealed red crystalline ampoule', layers: ['#BE123C', '#E11D48', '#FB7185', '#FFE4E6'] },
  { id: 'cosmic_tube', name: 'Stardust Column', styleType: 'cosmic_tube', price: 1250, desc: 'Stellar constellation glass', layers: ['#4C1D95', '#6D28D9', '#8B5CF6', '#DDD6FE'] },
  { id: 'amber_tube', name: 'Fossil Amber', styleType: 'amber_tube', price: 1300, desc: 'Ancient petrified tree resin', layers: ['#92400E', '#B45309', '#D97706', '#FDE68A'] },
  { id: 'amethyst_tube', name: 'Amethyst Shard', styleType: 'amethyst_tube', price: 1350, desc: 'Raw purple quartz crystal', layers: ['#581C87', '#7E22CE', '#A855F7', '#F3E8FF'] },
  { id: 'solar_tube', name: 'Helios Ray', styleType: 'solar_tube', price: 1400, desc: 'Sunburst ionized glass cylinder', layers: ['#C2410C', '#EA580C', '#F97316', '#FED7AA'] },
  { id: 'aquarium_tube', name: 'Coral Column', styleType: 'aquarium_tube', price: 1450, desc: 'Micro marine habitat tube', layers: ['#0E7490', '#06B6D4', '#38BDF8', '#E0F2FE'] },
  { id: 'abyss_tube', name: 'Abyssal Trench', styleType: 'abyss_tube', price: 1500, desc: 'Midnight bioluminescent depth', layers: ['#1E1B4B', '#312E81', '#4338CA', '#818CF8'] },
  { id: 'alchemy_tube', name: 'Philosopher Rod', styleType: 'alchemy_tube', price: 1550, desc: 'Transmutation runic glass', layers: ['#854D0E', '#CA8A04', '#EAB308', '#FEF08A'] },
  { id: 'storm_tube', name: 'Tempest Arc', styleType: 'storm_tube', price: 1600, desc: 'Lightning trapped inside glass', layers: ['#1D4ED8', '#2563EB', '#60A5FA', '#BFDBFE'] },
  { id: 'lotus_tube', name: 'Lotus Stalk', styleType: 'lotus_tube', price: 1650, desc: 'Graceful floral gradient', layers: ['#9D174D', '#BE185D', '#EC4899', '#FBCFE8'] },
  { id: 'copper_tube', name: 'Copper Patina', styleType: 'copper_tube', price: 1700, desc: 'Aged verdigris copper rim', layers: ['#0F766E', '#14B8A6', '#2DD4BF', '#99F6E4'] },
  { id: 'titanium_tube', name: 'Titanium Shell', styleType: 'titanium_tube', price: 1750, desc: 'Ultra-light space alloy frame', layers: ['#334155', '#475569', '#64748B', '#CBD5E1'] },
  { id: 'dark_matter_tube', name: 'Dark Matter Void', styleType: 'dark_matter_tube', price: 1800, desc: 'Gravitational singularity tube', layers: ['#0F172A', '#1E293B', '#334155', '#94A3B8'] },
  { id: 'celestial_tube', name: 'Celestial Pillar', styleType: 'celestial_tube', price: 1850, desc: 'Angelic divine light column', layers: ['#F59E0B', '#EC4899', '#635BFF', '#06B6D4'] },
  { id: 'supernova_tube', name: 'Supernova Burst', styleType: 'supernova_tube', price: 1900, desc: 'Dying star stellar eruption', layers: ['#DC2626', '#F59E0B', '#3B82F6', '#8B5CF6'] },
  { id: 'time_tube', name: 'Chronos Helix', styleType: 'time_tube', price: 1950, desc: 'Temporal flow distortion tube', layers: ['#6366F1', '#8B5CF6', '#D946EF', '#06B6D4'] },
  { id: 'infinity_tube', name: 'Infinity Prism', styleType: 'infinity_tube', price: 2000, desc: 'Transcendent infinite spectrum', layers: ['#635BFF', '#06B6D4', '#22C55E', '#F59E0B'] },
];
